import type { CSSProperties } from 'react'

export const editableRootStyle = {
  // e27-inspired professional platform: blue accent, clean white surfaces,
  // light gray page background, dark navy sections, modern professional typography.
  '--slot4-page-bg': '#f4f5f7',
  '--slot4-page-text': '#111827',
  '--slot4-panel-bg': '#ffffff',
  '--slot4-surface-bg': '#ffffff',
  '--slot4-muted-text': '#6b7280',
  '--slot4-soft-muted-text': '#9ca3af',
  '--slot4-accent': '#1d6fe8',
  '--slot4-accent-fill': '#1d6fe8',
  '--slot4-accent-soft': '#eff6ff',
  '--slot4-on-accent': '#ffffff',
  '--slot4-dark-bg': '#1e2a4a',
  '--slot4-dark-text': '#ffffff',
  '--slot4-media-bg': '#e5e7eb',
  '--slot4-cream': '#ffffff',
  '--slot4-warm': '#f9fafb',
  '--slot4-lavender': '#eff6ff',
  '--slot4-gray': '#f4f5f7',
  '--slot4-body-gradient': 'none',
  '--slot4-secondary': '#16a34a',
  '--editable-page-bg': '#f4f5f7',
  '--editable-page-text': '#111827',
  '--editable-container': '1440px',
  '--editable-border': '#e2e5ea',
  '--editable-nav-bg': '#ffffff',
  '--editable-nav-text': '#374151',
  '--editable-nav-active': '#1d6fe8',
  '--editable-nav-active-text': '#ffffff',
  '--editable-cta-bg': '#1d6fe8',
  '--editable-cta-text': '#ffffff',
  '--editable-search-bg': '#f4f5f7',
  '--editable-footer-bg': '#111827',
  '--editable-footer-text': '#e5e7eb',
} as CSSProperties

export const editablePalette = {
  pageBg: 'bg-[var(--slot4-page-bg)]',
  pageText: 'text-[var(--slot4-page-text)]',
  panelBg: 'bg-[var(--slot4-panel-bg)]',
  panelText: 'text-[var(--slot4-page-text)]',
  surfaceBg: 'bg-[var(--slot4-surface-bg)]',
  surfaceText: 'text-[var(--slot4-page-text)]',
  mutedText: 'text-[var(--slot4-muted-text)]',
  softMutedText: 'text-[var(--slot4-soft-muted-text)]',
  accentText: 'text-[var(--slot4-accent)]',
  accentBg: 'bg-[var(--slot4-accent-fill)]',
  accentSoftBg: 'bg-[var(--slot4-accent-soft)]',
  accentSoftText: 'text-[var(--slot4-accent-soft)]',
  onAccentText: 'text-[var(--slot4-on-accent)]',
  darkBg: 'bg-[var(--slot4-dark-bg)]',
  darkText: 'text-[var(--slot4-dark-text)]',
  mediaBg: 'bg-[var(--slot4-media-bg)]',
  creamBg: 'bg-[var(--slot4-cream)]',
  warmBg: 'bg-[var(--slot4-warm)]',
  lavenderBg: 'bg-[var(--slot4-lavender)]',
  grayBg: 'bg-[var(--slot4-gray)]',
  border: 'border-[var(--editable-border)]',
  darkBorder: 'border-white/10',
  shadow: 'shadow-[0_1px_3px_rgba(0,0,0,0.08)]',
  shadowStrong: 'shadow-[0_4px_18px_rgba(0,0,0,0.12)]',
  overlay: 'bg-[linear-gradient(180deg,rgba(0,0,0,0.02),rgba(0,0,0,0.72))]',
} as const

export const editableDesignContract = {
  shell: {
    page: `min-h-screen ${editablePalette.pageBg} ${editablePalette.pageText}`,
    section: 'mx-auto w-full max-w-7xl px-4 sm:px-6 lg:px-8',
    sectionY: 'py-10 sm:py-12 lg:py-16',
  },
  layout: {
    safeGrid: 'grid gap-6 md:grid-cols-2 xl:grid-cols-3',
    featureGrid: 'grid gap-12 lg:grid-cols-[1.05fr_0.95fr] lg:items-center',
    rail: 'flex snap-x gap-5 overflow-x-auto pb-4 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden',
    minRailCard: 'w-[280px] shrink-0 snap-start sm:w-[300px]',
  },
  type: {
    eyebrow: 'text-xs font-semibold uppercase tracking-[0.24em] text-[var(--slot4-accent)]',
    heroTitle: 'text-3xl font-bold leading-[1.1] tracking-[-0.02em] sm:text-4xl lg:text-5xl',
    sectionTitle: 'text-xl font-bold tracking-[-0.01em] sm:text-2xl',
    body: 'text-base leading-relaxed',
  },
  surface: {
    card: `rounded-xl border ${editablePalette.border} ${editablePalette.surfaceBg} ${editablePalette.shadow}`,
    soft: `rounded-xl border ${editablePalette.border} ${editablePalette.panelBg}`,
    dark: `rounded-xl ${editablePalette.darkBg} ${editablePalette.darkText} ${editablePalette.shadowStrong}`,
  },
  button: {
    primary: `inline-flex items-center justify-center gap-2 rounded-full bg-[var(--slot4-accent-fill)] px-5 py-2.5 text-sm font-semibold text-[var(--slot4-on-accent)] transition duration-200 hover:brightness-95 active:scale-[0.98]`,
    secondary: `inline-flex items-center justify-center gap-2 rounded-full border border-[var(--editable-border)] bg-[var(--slot4-surface-bg)] px-5 py-2.5 text-sm font-semibold text-[var(--slot4-page-text)] transition duration-200 hover:border-[var(--slot4-accent)] hover:text-[var(--slot4-accent)] active:scale-[0.98]`,
    accent: `inline-flex items-center justify-center gap-2 rounded-full ${editablePalette.accentBg} px-5 py-2.5 text-sm font-semibold text-[var(--slot4-on-accent)] transition duration-200 hover:brightness-95 active:scale-[0.98]`,
    signup: `inline-flex items-center justify-center gap-2 rounded-full bg-[#16a34a] px-5 py-2.5 text-sm font-semibold text-white transition duration-200 hover:brightness-95 active:scale-[0.98]`,
  },
  media: {
    frame: `relative overflow-hidden rounded-xl ${editablePalette.mediaBg}`,
    ratio: 'aspect-[16/10]',
  },
  motion: {
    lift: 'transition duration-200 hover:-translate-y-0.5 hover:shadow-[0_8px_24px_rgba(0,0,0,0.12)]',
    fade: 'transition duration-200 hover:opacity-80',
  },
} as const

export const aiLayoutRules = [
  'Change the full site color palette in editableRootStyle first; all homepage sections consume those CSS variables.',
  'Keep page structure in src/editable/sections/HomeSections.tsx so AI can redesign the whole home experience in one file.',
  'Use wide readable grids; never create skinny columns for paragraphs or cards.',
  'Use horizontal rails for dense post browsing, like the e27 reference layout.',
  'Keep dynamic post fetching intact; do not replace posts with mock arrays.',
  'Use postHref() for all post links so task-specific routes keep working.',
] as const
